In [1]:
import numpy as np

In [ ]:
arr = np.arange(0, 30, 3) #cria um array com os numeros de 0 a 30, pulando de 3 em 3

In [ ]:
arr #printa o array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
arr[3] #pega o elemento do indice 3, ou seja, o quarto elemento do array, que é o numero 9

np.int64(9)

In [ ]:
arr[2:5] #pega os elementos dos indices 2, 3 e 4

array([ 6,  9, 12])

In [ ]:
arr[:5] #pega os elementos dos indices 0, 1, 2, 3 e 4

array([ 0,  3,  6,  9, 12])

In [ ]:
arr[2:] #pega os elementos dos indices 2, 3, 4, 5, 6, 7 e 8

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
arr[2:] = 100 #atribui o valor 100 para os elementos dos indices 2, 3, 4, 5, 6, 7 e 8

In [ ]:
arr #o array agora tem os valores 0, 3, 100, 100, 100, 100, 100, 100, 100 e 27

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr = np.arange(50).reshape((5,10)) #cria um array com os numeros de 0 a 49 e o reshape transforma esse array em uma matriz de 5 linhas e 10 colunas

In [ ]:
arr #o array agora tem os valores 0, 3, 100, 100, 100, 100, 100, 100, 100 e 27

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr.shape #mostra a forma do array, ou seja, o numero de linhas e colunas da matriz, que é 5 linhas e 10 colunas

(5, 10)

In [ ]:
arr[:3][:] #pega os elementos dos indices 0, 1 e 2, ou seja, as primeiras 3 linhas da matriz, e o : depois do primeiro : pega todas as colunas dessas linhas

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
arr2 = arr[:3] #cria um novo array chamado arr2 que recebe os elementos dos indices 0, 1 e 2, ou seja, as primeiras 3 linhas da matriz, e o : depois do primeiro : pega todas as colunas dessas linhas

In [ ]:
arr2 #printa o array arr2, o resultado ta printado ai

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
arr2[:] = 100 #atribui o valor 100 para todos os elementos do array arr2

In [18]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [19]:
arr2 = arr[:3].copy()

In [20]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [21]:
arr2[:] = 10

In [22]:
arr2

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [23]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [24]:
arr[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [25]:
arr > 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [26]:
bol = arr > 50

In [27]:
arr bol

SyntaxError: invalid syntax (4015766192.py, line 1)

In [28]:
arr[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [29]:
array = np.linspace(0, 100, 30)

In [31]:
array

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [32]:
array.shape

(30,)

In [33]:
array = array.reshape(3, 10)

In [34]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [35]:
array.shape

(3, 10)

In [36]:
array[0:2, 2]

array([ 6.89655172, 41.37931034])

In [53]:
array[0:2, 9] 

array([31.03448276, 65.51724138])